// In-memory resilient store for standalone local development without PostgreSQL daemon
export interface MockStoreType {
  project: any;
  members: any[];
  tasks: any[];
  milestones: any[];
  sprints: any[];
  blockers: any[];
  sihReadinessItems: any[];
  demoChecklistItems: any[];
  activities: any[];
  meetings: any[];
  documents: any[];
  bugs: any[];
  testCases: any[];
  risks: any[];
  comments: Record<string, any[]>;
  workstreams: any[];
}

export const mockStore: MockStoreType = {
  project: {
    id: 'proj-acadshield-001',
    projectId: 'proj-acadshield-001',
    name: 'AcadShield',
    problemStatementNumber: '1422',
    sihProblemStatement: 'SIH Problem Statement #1422: Tamper-proof academic credential issuance and verification ecosystem leveraging decentralized blockchain ledgers and zero-knowledge identity proofs.',
    description: 'AcadShield is a decentralized academic credential platform that enables universities to issue tamper-proof certificates, students to maintain verifiable credential wallets, and employers to verify authentic credentials in sub-seconds.',
    objective: 'Eliminate academic degree forgery through cryptographic hashing, W3C Decentralized Identifiers (DIDs), Hyperledger Fabric private ledgers, and automated fraud scoring.',
    repositoryUrl: 'https://github.com/vishanth11/AcadShield.git',
    progress: 72,
    status: 'ACTIVE',
    currentPhase: 'Phase 2 - Core Integration & UI Hardening',
    startDate: '2026-08-01',
    targetDate: '2026-09-15',
  },
  members: [
    {
      id: 'usr-lead-001',
      name: 'Member 1',
      email: 'lead@sihflow.io',
      role: 'TEAM_LEAD',
      teamRole: 'Team Lead',
      githubUsername: 'member1-lead',
      phone: '+91 98765 43210',
      responsibilities: 'Overall system architecture, integration coordination, dashboard integration, pull request reviews, final demo presentation, and SIH jury coordination.',
      currentTask: { taskId: 'TASK-101', title: 'Finalize System Architecture & Sequence Diagrams', progress: 100 },
      stats: { totalTasks: 4, completedTasks: 4, inProgressTasks: 0, blockedTasks: 0, completionRate: 100 },
    },
    {
      id: 'usr-github-002',
      name: 'Member 2',
      email: 'github@sihflow.io',
      role: 'TEAM_MEMBER',
      teamRole: 'GitHub / Developer Activity',
      githubUsername: 'member2-github',
      phone: '+91 98765 43211',
      responsibilities: 'GitHub API integration, webhook ingestion, repository sync, commit logs, pull requests tracking, issues triage, and developer activity metrics.',
      currentTask: { taskId: 'TASK-102', title: 'Implement Hyperledger Fabric Chaincode (credentialContract.js)', progress: 80 },
      stats: { totalTasks: 5, completedTasks: 3, inProgressTasks: 1, blockedTasks: 1, completionRate: 60 },
    },
    {
      id: 'usr-sec-003',
      name: 'Member 3',
      email: 'security@sihflow.io',
      role: 'TEAM_MEMBER',
      teamRole: 'Authentication / Security',
      githubUsername: 'member3-security',
      phone: '+91 98765 43212',
      responsibilities: 'Authentication, registration, JWT/session management, RBAC, protected routes, audit logging, security validation, and threat modeling.',
      currentTask: { taskId: 'TASK-103', title: 'Implement W3C DID Resolution & Merkle Hash Engine', progress: 90 },
      stats: { totalTasks: 4, completedTasks: 3, inProgressTasks: 1, blockedTasks: 0, completionRate: 75 },
    },
    {
      id: 'usr-backend-004',
      name: 'Member 4',
      email: 'backend@sihflow.io',
      role: 'TEAM_MEMBER',
      teamRole: 'Backend / Database',
      githubUsername: 'member4-backend',
      phone: '+91 98765 43213',
      responsibilities: 'PostgreSQL database design, Prisma ORM schema & migrations, REST APIs, projects, tasks, subtasks, milestones, sprints, dependencies, and blocker engines.',
      currentTask: { taskId: 'TASK-104', title: 'Build Express.js REST API & PostgreSQL Models', progress: 75 },
      stats: { totalTasks: 6, completedTasks: 4, inProgressTasks: 2, blockedTasks: 0, completionRate: 67 },
    },
    {
      id: 'usr-front-005',
      name: 'Member 5',
      email: 'frontend@sihflow.io',
      role: 'TEAM_MEMBER',
      teamRole: 'Frontend',
      githubUsername: 'member5-frontend',
      phone: '+91 98765 43214',
      responsibilities: 'React 18 + Vite + Tailwind CSS web interface, responsive dashboard, interactive Kanban board, team roster, milestones roadmap, sprints, activity feed, and notifications.',
      currentTask: { taskId: 'TASK-105', title: 'Develop Student Wallet & Public QR Verification UI', progress: 70 },
      stats: { totalTasks: 5, completedTasks: 3, inProgressTasks: 2, blockedTasks: 0, completionRate: 60 },
    },
    {
      id: 'usr-qa-006',
      name: 'Member 6',
      email: 'qa@sihflow.io',
      role: 'REVIEWER',
      teamRole: 'QA / UI-UX / Documentation',
      githubUsername: 'member6-qa',
      phone: '+91 98765 43215',
      responsibilities: 'Automated test suites (Vitest/Supertest), test case catalog, defect tracking, E2E testing, UI/UX audit, Software Requirements (SRS), SIH readiness assessment, and live demo checklist.',
      currentTask: { taskId: 'TASK-106', title: 'Create Vitest QA Automation & Tamper-Proof Test Cases', progress: 85 },
      stats: { totalTasks: 5, completedTasks: 4, inProgressTasks: 1, blockedTasks: 0, completionRate: 80 },
    },
  ],
  tasks: [
    {
      id: 't-101',
      taskId: 'TASK-101',
      title: 'Finalize System Architecture & Sequence Diagrams',
      description: 'Define microservices boundaries, Fabric ledger adapter interface, and PostgreSQL storage fallbacks.',
      priority: 'CRITICAL',
      status: 'DONE',
      progress: 100,
      assignee: { id: 'usr-lead-001', name: 'Member 1', teamRole: 'Team Lead' },
      milestoneId: 'm-2',
      milestone: { name: 'M2: Architecture' },
      dueDate: '2026-08-10',
      githubBranch: 'feature/integration',
    },
    {
      id: 't-102',
      taskId: 'TASK-102',
      title: 'Implement Hyperledger Fabric Chaincode (credentialContract.js)',
      description: 'Develop chaincode methods for issueCredential, verifyCredential, revokeCredential, and queryHistory.',
      priority: 'CRITICAL',
      status: 'IN_PROGRESS',
      progress: 80,
      assignee: { id: 'usr-github-002', name: 'Member 2', teamRole: 'GitHub / Developer Activity' },
      milestoneId: 'm-4',
      milestone: { name: 'M4: Blockchain Integration' },
      dueDate: '2026-08-25',
      githubBranch: 'feature/github',
    },
    {
      id: 't-103',
      taskId: 'TASK-103',
      title: 'Implement W3C DID Resolution & Merkle Hash Engine',
      description: 'Generate institutional did:acad identifiers, calculate certificate Merkle root hashes, and detect alterations.',
      priority: 'HIGH',
      status: 'IN_REVIEW',
      progress: 90,
      assignee: { id: 'usr-sec-003', name: 'Member 3', teamRole: 'Authentication / Security' },
      milestoneId: 'm-3',
      milestone: { name: 'M3: Core Development' },
      dueDate: '2026-08-20',
      githubBranch: 'feature/auth-security',
    },
    {
      id: 't-104',
      taskId: 'TASK-104',
      title: 'Build Express.js REST API & PostgreSQL Models',
      description: 'Create endpoints for /api/credentials/issue, /api/verify, /api/students, and multi-tenant DB schema.',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      progress: 75,
      assignee: { id: 'usr-backend-004', name: 'Member 4', teamRole: 'Backend / Database' },
      milestoneId: 'm-3',
      milestone: { name: 'M3: Core Development' },
      dueDate: '2026-08-22',
      githubBranch: 'feature/backend',
    },
    {
      id: 't-105',
      taskId: 'TASK-105',
      title: 'Develop Student Wallet & Public QR Verification UI',
      description: 'Build React 18 responsive interfaces for certificate viewer, QR code scanner, and drag-and-drop verification.',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      progress: 70,
      assignee: { id: 'usr-front-005', name: 'Member 5', teamRole: 'Frontend' },
      milestoneId: 'm-5',
      milestone: { name: 'M5: Frontend + Backend Integration' },
      dueDate: '2026-08-30',
      githubBranch: 'feature/frontend',
    },
    {
      id: 't-106',
      taskId: 'TASK-106',
      title: 'Create Vitest QA Automation & Tamper-Proof Test Cases',
      description: 'Author unit & integration test suites covering happy path issuance, hash tampering, and unauthorized access.',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      progress: 85,
      assignee: { id: 'usr-qa-006', name: 'Member 6', teamRole: 'QA / UI-UX / Documentation' },
      milestoneId: 'm-6',
      milestone: { name: 'M6: Testing' },
      dueDate: '2026-09-02',
      githubBranch: 'feature/qa-docs',
    },
    {
      id: 't-107',
      taskId: 'TASK-107',
      title: 'Configure Hyperledger Peer TLS Certificates',
      description: 'Mount cryptographic peer certificate authorities for secure node gossip protocol.',
      priority: 'HIGH',
      status: 'BLOCKED',
      progress: 40,
      assignee: { id: 'usr-github-002', name: 'Member 2', teamRole: 'GitHub / Developer Activity' },
      milestoneId: 'm-4',
      milestone: { name: 'M4: Blockchain Integration' },
      dueDate: '2026-08-28',
      githubBranch: 'feature/github',
    },
  ],
  milestones: [
    { id: 'm-1', milestoneCode: 'M1', name: 'Problem Understanding', description: 'Deep dive into SIH Problem Statement #1422 requirements, stakeholders, and workflow.', progress: 100, status: 'Completed', deadline: '2026-08-05' },
    { id: 'm-2', milestoneCode: 'M2', name: 'Architecture', description: 'System architecture freeze, sequence diagrams, database schemas, and threat modeling.', progress: 100, status: 'Completed', deadline: '2026-08-10' },
    { id: 'm-3', milestoneCode: 'M3', name: 'Core Development', description: 'Implementation of core credential issuance, hashing, and database storage.', progress: 90, status: 'On Track', deadline: '2026-08-18' },
    { id: 'm-4', milestoneCode: 'M4', name: 'Blockchain Integration', description: 'Hyperledger Fabric network setup, chaincode smart contract deployment, and adapter.', progress: 75, status: 'At Risk', deadline: '2026-08-25' },
    { id: 'm-5', milestoneCode: 'M5', name: 'Frontend + Backend Integration', description: 'Issuer dashboard, Student credential wallet, and public verification UI integration.', progress: 70, status: 'On Track', deadline: '2026-08-30' },
    { id: 'm-6', milestoneCode: 'M6', name: 'Testing', description: 'Unit testing, integration testing, Supertest suites, and load test scripts.', progress: 80, status: 'On Track', deadline: '2026-09-02' },
    { id: 'm-7', milestoneCode: 'M7', name: 'Security Validation', description: 'Tamper proof tests, replay attack prevention, RBAC audit, and Merkle root verification.', progress: 65, status: 'On Track', deadline: '2026-09-05' },
    { id: 'm-8', milestoneCode: 'M8', name: 'Deployment', description: 'Docker containerization, Docker-Compose multi-container orchestration, and reverse proxy.', progress: 85, status: 'On Track', deadline: '2026-09-08' },
    { id: 'm-9', milestoneCode: 'M9', name: 'Documentation', description: 'Software Requirements Specification (SRS), API documentation, User Guide, and Demo script.', progress: 90, status: 'On Track', deadline: '2026-09-10' },
    { id: 'm-10', milestoneCode: 'M10', name: 'Final Demo', description: 'End-to-end dry runs of live jury evaluation scenarios with zero fail rates.', progress: 50, status: 'On Track', deadline: '2026-09-12' },
    { id: 'm-11', milestoneCode: 'M11', name: 'SIH Presentation', description: 'Grand Finale pitch deck, value proposition slides, and architectural presentation.', progress: 40, status: 'On Track', deadline: '2026-09-15' },
  ],
  sprints: [
    { id: 's-1', number: 1, name: 'Sprint 1 — Core Prototype', goal: 'Establish PostgreSQL schemas, credential issuance hashing, and mock ledger.', progress: 100, status: 'COMPLETED', velocity: 38, totalTasks: 6, completedTasks: 6, inProgressTasks: 0, blockedTasks: 0, startDate: '2026-08-01', endDate: '2026-08-10' },
    { id: 's-2', number: 2, name: 'Sprint 2 — Blockchain & UI Integration', goal: 'Integrate Fabric chaincode, student wallet, QR code verification, and fraud scoring.', progress: 70, status: 'ACTIVE', velocity: 38, totalTasks: 8, completedTasks: 5, inProgressTasks: 2, blockedTasks: 1, startDate: '2026-08-11', endDate: '2026-08-25' },
    { id: 's-3', number: 3, name: 'Sprint 3 — Demo Polish & Hardening', goal: 'Complete test automation, load testing, SRS documentation, and SIH jury rehearsal.', progress: 25, status: 'PLANNED', velocity: 40, totalTasks: 7, completedTasks: 1, inProgressTasks: 2, blockedTasks: 0, startDate: '2026-08-26', endDate: '2026-09-15' },
  ],
  blockers: [
    {
      id: 'blk-001',
      blockerId: 'BLK-001',
      title: 'Awaiting Fabric Peer Gateway Endorsement TLS Config',
      description: 'Backend cannot submit transaction blocks to channel mychannel until TLS client certs are mounted.',
      reporter: { name: 'Member 4 (Backend)' },
      blockedUser: { name: 'Member 2 (GitHub / Activity)' },
      priority: 'HIGH',
      status: 'OPEN',
      impact: 'Delays end-to-end credential anchoring test runs.',
      createdAt: new Date().toISOString(),
    },
  ],
  sihReadinessItems: [
    { id: 'r-1', category: 'Problem Understanding', name: 'Problem Statement Understanding (#1422)', description: 'Full requirements analysis, stakeholder mapping, and scope definition.', status: 'Completed', progress: 100 },
    { id: 'r-2', category: 'Architecture', name: 'Decentralized Multi-Peer System Architecture', description: 'Fabric network design, cryptographic hash flow, and relational data model.', status: 'Completed', progress: 100 },
    { id: 'r-3', category: 'Development', name: 'Core Credential Issuance & Student Wallet', description: 'REST APIs, React wallet, and certificate cryptographic generator.', status: 'In Progress', progress: 85 },
    { id: 'r-4', category: 'Integration', name: 'Blockchain Ledger & QR Verification Adapter', description: 'Hyperledger Fabric chaincode integration with real-time verification endpoint.', status: 'In Progress', progress: 80 },
    { id: 'r-5', category: 'Testing', name: 'Automated Vitest/Supertest QA Pipeline', description: '12/12 test suites verifying happy path, tampering detection, and RBAC.', status: 'Completed', progress: 100 },
    { id: 'r-6', category: 'Security', name: 'W3C DIDs & Byte-Level Tamper Detection', description: 'SHA-256 Merkle root verification and replay attack mitigations.', status: 'In Progress', progress: 90 },
    { id: 'r-7', category: 'Documentation', name: 'Software Requirements Specification (SRS v1.0)', description: 'Complete system architecture, API documentation, and user guides.', status: 'Completed', progress: 100 },
    { id: 'r-8', category: 'Deployment', name: 'Docker Compose & NGINX Local Infrastructure', description: 'Multi-stage container orchestration with isolated networks.', status: 'In Progress', progress: 85 },
    { id: 'r-9', category: 'Demo', name: 'Live SIH Jury Evaluation Dry Run Scenarios', description: 'Zero-fail scripted demo covering issuance, verification, tampering, and revocation.', status: 'In Progress', progress: 75 },
  ],
  demoChecklistItems: [
    { id: 'd-1', itemCode: 'DEMO-01', category: 'ISSUANCE', title: 'University Issues Credential', description: 'Admin issues B.Tech Degree with SHA-256 hash and metadata.', expectedResult: 'HTTP 201 Created + Block Hash generated on ledger', status: 'PASS' },
    { id: 'd-2', itemCode: 'DEMO-02', category: 'WALLET', title: 'Student Receives in Wallet', description: 'Student logs in, views verifiable credential, and generates QR code.', expectedResult: 'QR code rendered with signed payload', status: 'PASS' },
    { id: 'd-3', itemCode: 'DEMO-03', category: 'VERIFICATION', title: 'Public QR Verification', description: 'Employer scans QR code to verify authenticity in sub-seconds.', expectedResult: 'Instant Green Verified Badge displayed', status: 'PASS' },
    { id: 'd-4', itemCode: 'DEMO-04', category: 'TAMPER_DETECTION', title: 'Tamper Detection Rehearsal', description: 'Upload altered PDF certificate with modified GPA or student name.', expectedResult: 'Instant Red Tampered Warning + Fraud Alert logged', status: 'PASS' },
    { id: 'd-5', itemCode: 'DEMO-05', category: 'REVOCATION', title: 'Credential Revocation', description: 'Issuer revokes certificate due to administrative request.', expectedResult: 'Status updates to REVOKED on ledger verification', status: 'PASS' },
  ],
  activities: [
    { id: 'act-1', summary: 'Member 1 finalized System Architecture and Sequence Diagrams', eventType: 'TASK_COMPLETED', user: { name: 'Member 1', teamRole: 'Team Lead' }, createdAt: new Date(Date.now() - 3600000 * 2).toISOString() },
    { id: 'act-2', summary: 'Member 2 updated Hyperledger Fabric chaincode integration (credentialContract.js)', eventType: 'TASK_UPDATED', user: { name: 'Member 2', teamRole: 'GitHub / Developer Activity' }, createdAt: new Date(Date.now() - 3600000 * 4).toISOString() },
    { id: 'act-3', summary: 'Member 3 submitted W3C DID Resolution for architectural code review', eventType: 'TASK_REVIEW_REQUESTED', user: { name: 'Member 3', teamRole: 'Authentication / Security' }, createdAt: new Date(Date.now() - 3600000 * 6).toISOString() },
    { id: 'act-4', summary: 'Member 4 reported blocker: Awaiting Fabric Peer Gateway Endorsement TLS Config', eventType: 'BLOCKER_REPORTED', user: { name: 'Member 4', teamRole: 'Backend / Database' }, createdAt: new Date(Date.now() - 3600000 * 8).toISOString() },
    { id: 'act-5', summary: 'Member 5 updated Student Wallet & Public QR Verification UI', eventType: 'TASK_UPDATED', user: { name: 'Member 5', teamRole: 'Frontend' }, createdAt: new Date(Date.now() - 3600000 * 12).toISOString() },
    { id: 'act-6', summary: 'Member 6 executed 12/12 automated integration tests with 100% pass rate', eventType: 'TESTS_PASSED', user: { name: 'Member 6', teamRole: 'QA / UI-UX / Documentation' }, createdAt: new Date(Date.now() - 3600000 * 24).toISOString() },
  ],
  meetings: [
    {
      id: 'mtg-001',
      title: 'Daily Standup #14 — Sprint 2 Check-in',
      date: '2026-08-30',
      time: '09:30 AM',
      type: 'DAILY_STANDUP',
      participants: 'All 6 Team Members',
      durationMinutes: 20,
      agenda: '1. Blocker review on Fabric TLS certificates\n2. Review W3C DID PR (#5)\n3. Verify QR scanner response times',
      notes: 'Member 2 will finalize the TLS cert mounting script today. Member 4 will connect the Express verification route.',
      scheduledAt: new Date().toISOString(),
    },
    {
      id: 'mtg-002',
      title: 'Architecture Review & Demo Rehearsal Prep',
      date: '2026-09-02',
      time: '04:00 PM',
      type: 'ARCHITECTURE_SYNC',
      participants: 'Member 1, Member 2, Member 3, Member 6',
      durationMinutes: 45,
      agenda: '1. Walkthrough 5-minute SIH live jury script\n2. Validate tamper rejection live response\n3. Slide deck review',
      notes: 'Ensure backup video recording of blockchain transaction ledger is ready in case of venue network latency.',
      scheduledAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    },
  ],
  documents: [
    {
      id: 'doc-001',
      title: 'AcadShield SRS Specification (WS-14)',
      type: 'SRS',
      category: 'SPECIFICATION',
      version: '1.0.0',
      owner: { name: 'Member 6 (QA / UI-UX / Docs)' },
      author: { name: 'Member 6', teamRole: 'QA / UI-UX / Documentation' },
      date: '2026-08-20',
      status: 'APPROVED',
      reviewStatus: 'APPROVED',
      content: 'Complete Software Requirements Specification covering IEEE 830 standards, functional requirements for university issuers, student wallets, employer verifiers, and Hyperledger smart contracts.',
      updatedAt: '2026-08-20',
    },
    {
      id: 'doc-002',
      title: 'System Architecture & Sequence Diagrams (WS-01)',
      type: 'ARCH_DOC',
      category: 'ARCHITECTURE',
      version: '1.2.0',
      owner: { name: 'Member 1 (Team Lead)' },
      author: { name: 'Member 1', teamRole: 'Team Lead' },
      date: '2026-08-22',
      status: 'APPROVED',
      reviewStatus: 'APPROVED',
      content: 'High-level component diagrams, sequence diagrams for credential issuance and verification, database entity relationships, and Docker topology.',
      updatedAt: '2026-08-22',
    },
    {
      id: 'doc-003',
      title: 'API Interface Contract & OpenAPI v3 (WS-07)',
      type: 'API_SPEC',
      category: 'SPECIFICATION',
      version: '1.0.0',
      owner: { name: 'Member 4 (Backend)' },
      author: { name: 'Member 4', teamRole: 'Backend / Database' },
      date: '2026-08-25',
      status: 'APPROVED',
      reviewStatus: 'APPROVED',
      content: 'REST API endpoints for issuance, student wallets, verification, and revocation with JSON schema payloads.',
      updatedAt: '2026-08-25',
    },
  ],
  bugs: [
    {
      id: 'bug-001',
      bugId: 'BUG-001',
      title: 'Certificate QR scanner throws format error on iOS Safari',
      description: 'The html5-qrcode scanner video stream requires explicit playsInline attribute on Safari mobile.',
      severity: 'HIGH',
      status: 'OPEN',
      reporter: { id: 'usr-qa-006', name: 'Member 6 (QA)' },
      assignee: { id: 'usr-front-005', name: 'Member 5 (Frontend)' },
      createdAt: new Date().toISOString(),
    },
    {
      id: 'bug-002',
      bugId: 'BUG-002',
      title: 'Missing input validation on student roll number format',
      description: 'Issuance endpoint accepted spaces in roll number field which broke QR URL generation.',
      severity: 'MEDIUM',
      status: 'RESOLVED',
      reporter: { id: 'usr-qa-006', name: 'Member 6 (QA)' },
      assignee: { id: 'usr-backend-004', name: 'Member 4 (Backend)' },
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  testCases: [
    {
      id: 'tc-001',
      testCaseId: 'TC-01',
      feature: 'Credential Issuance Flow',
      description: 'Validate complete issuer signing and SHA-256 certificate generation.',
      steps: '1. Login as University Admin\n2. Issue degree certificate\n3. Check database record',
      expectedResult: 'HTTP 201 Created with valid hash and DID',
      status: 'PASS',
      executionTimeMs: 42,
    },
    {
      id: 'tc-002',
      testCaseId: 'TC-02',
      feature: 'Tamper Detection Engine',
      description: 'Detect modified GPA in PDF and ensure verification fails.',
      steps: '1. Alter GPA byte in PDF\n2. Upload to /api/verify\n3. Check response status',
      expectedResult: 'HTTP 200 OK with isValid: false and fraud alert',
      status: 'PASS',
      executionTimeMs: 38,
    },
    {
      id: 'tc-003',
      testCaseId: 'TC-03',
      feature: 'W3C DID Resolution',
      description: 'Resolve institutional DID and verify cryptographic public key.',
      steps: '1. Query did:acad:university-01\n2. Verify signature',
      expectedResult: 'Returns DID Document with verified Ed25519 key',
      status: 'PASS',
      executionTimeMs: 25,
    },
    {
      id: 'tc-004',
      testCaseId: 'TC-04',
      feature: 'Hyperledger Fabric Chaincode Adapter',
      description: 'Submit transaction to chaincode and read back committed block state.',
      steps: '1. Invoke issueCredential on peer0\n2. Query ledger state',
      expectedResult: 'Block successfully added with transaction ID',
      status: 'PASS',
      executionTimeMs: 68,
    },
    {
      id: 'tc-005',
      testCaseId: 'TC-05',
      feature: 'RBAC Authorization Check',
      description: 'Verify students cannot access university issuance routes.',
      steps: '1. Authenticate with student token\n2. Call POST /api/credentials/issue',
      expectedResult: 'HTTP 403 Forbidden',
      status: 'PASS',
      executionTimeMs: 14,
    },
  ],
  risks: [
    {
      id: 'risk-001',
      title: 'Grand Finale Live Demo Internet Latency',
      category: 'DEMO',
      probability: 'HIGH',
      impact: 'HIGH',
      severity: 'CRITICAL',
      mitigation: 'Implement local Dockerized Fabric peer container on presentation laptop with offline fallback.',
      owner: { name: 'Member 1 (Team Lead)' },
      status: 'MITIGATING',
    },
    {
      id: 'risk-002',
      title: 'Smart Contract Key Management Security',
      category: 'SECURITY',
      probability: 'MEDIUM',
      impact: 'HIGH',
      severity: 'HIGH',
      mitigation: 'Store university issuer private keys using environment variables and mock HSM vault.',
      owner: { name: 'Member 3 (Security)' },
      status: 'MONITORING',
    },
  ],
  comments: {
    't-101': [
      { id: 'c-1', text: 'Completed all sequence diagrams and pushed to /docs/architecture.md', author: { name: 'Member 1' }, createdAt: new Date(Date.now() - 3600000 * 4).toISOString() },
    ],
    't-102': [
      { id: 'c-2', text: 'Chaincode methods written for issueCredential and verifyCredential. Working on revokeCredential now.', author: { name: 'Member 2' }, createdAt: new Date(Date.now() - 3600000 * 2).toISOString() },
    ],
    't-103': [
      { id: 'c-3', text: 'DID resolver logic tested against Ed25519 key pairs. All crypto tests passing.', author: { name: 'Member 3' }, createdAt: new Date(Date.now() - 3600000 * 5).toISOString() },
    ],
  },
  workstreams: [
    { code: 'WS-01', name: 'System Architecture & Diagrams', owner: 'Member 1', progress: 100 },
    { code: 'WS-02', name: 'Hyperledger Fabric Chaincode', owner: 'Member 2', progress: 80 },
    { code: 'WS-03', name: 'W3C DID Cryptographic Engine', owner: 'Member 3', progress: 90 },
    { code: 'WS-04', name: 'Backend API & PostgreSQL Schema', owner: 'Member 4', progress: 75 },
    { code: 'WS-05', name: 'Student Wallet & QR Verifier UI', owner: 'Member 5', progress: 70 },
    { code: 'WS-06', name: 'Automated QA & Test Automation', owner: 'Member 6', progress: 85 },
  ],
};
